
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DA-ADHIRAMAHARANI
 */
public class DaftarAntrian extends javax.swing.JFrame {

    /**
     * Creates new form DaftarAntrian
     */
    public DaftarAntrian() {
        initComponents();
        tampilkanDataAntrian();
    }

    private void tampilkanDataAntrian() {
        String sql = "SELECT nomor_antrian, nama, jenis_kelamin, alamat, kondisi FROM antrian";

        try (
            Connection conn = KoneksiDB.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql)
        ) {
            DefaultTableModel model = new DefaultTableModel();
            TabelAntrian.setAutoCreateRowSorter(true);
            model.addColumn("Nomor Antrian");
            model.addColumn("Nama");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Alamat");
            model.addColumn("Kondisi");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("nomor_antrian"),
                    rs.getString("nama"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("alamat"),
                    rs.getString("kondisi")
                });
            }

            TabelAntrian.setModel(model); // Ganti dengan JTable Anda
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelAntrian = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tbPencarian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHapus.setText("Hapus");
        btnHapus.setToolTipText("");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        TabelAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Antrian", "Nama", "Jenis Kelamin", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(TabelAntrian);

        jLabel1.setText("Daftar Antrian");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah Antrian");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbah))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCari)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambah))
                    .addComponent(btnCari, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String q = tbPencarian.getText().trim();
        String keyword = "%" + q + "%";

        String sql = "SELECT * FROM antrian WHERE nama LIKE ? OR alamat LIKE ? OR nomor_antrian LIKE ?";

        try (
            Connection conn = KoneksiDB.getConnection(); // koneksi dibuat di sini
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {
            ps.setString(1, keyword);
            ps.setString(2, keyword);
            ps.setString(3, keyword);

            try (ResultSet rs = ps.executeQuery()) {
                DefaultTableModel model = new DefaultTableModel();
                TabelAntrian.setAutoCreateRowSorter(true);
                model.addColumn("Nomor Antrian");
                model.addColumn("Nama");
                model.addColumn("Jenis Kelamin");
                model.addColumn("Alamat");
                model.addColumn("Kondisi");

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("nomor_antrian"),
                        rs.getString("nama"),
                        rs.getString("jenis_kelamin"),
                        rs.getString("alamat"),
                        rs.getString("kondisi")
                    });
                }

                TabelAntrian.setModel(model); // <<== pastikan ini adalah JTable, bukan model!
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int selectedRow = TabelAntrian.getSelectedRow();
        if (selectedRow != -1) {
            String nomorAntrian = TabelAntrian.getValueAt(selectedRow, 0).toString();
            String nama = TabelAntrian.getValueAt(selectedRow, 1).toString();
            String jenisKelamin = TabelAntrian.getValueAt(selectedRow, 2).toString();
            String alamat = TabelAntrian.getValueAt(selectedRow, 3).toString();

            // Buka FormAntrian dan isi data
            FormUbahAntrian formAntrian = new FormUbahAntrian();
            formAntrian.setVisible(true);
            formAntrian.jTextField1.setText(nama);
            formAntrian.jComboBox1.setSelectedItem(jenisKelamin);
            formAntrian.jTextField2.setText(alamat);

            // Simpan nomor antrian ke dalam form untuk keperluan update
            formAntrian.no.setText(nomorAntrian);
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        FormAntrian formAntrian = new FormAntrian(); 
        formAntrian.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) { 
        // TODO add your handling code here:
        try {
            // Cek apakah ada baris yang dipilih di tabel
            int selectedRow = TabelAntrian.getSelectedRow();
            if (selectedRow == -1) {
                // Tampilkan pesan jika tidak ada baris yang terpilih
                jOptionPane1.showMessageDialog(this, "Silakan pilih data yang ingin dihapus.");
                return; // Keluar dari metode jika tidak ada baris yang dipilih
            }

            // Ambil nomor antrian yang terpilih
            String nomorAntrian = TabelAntrian.getValueAt(selectedRow, 0).toString();

            // Koneksi ke database dan eksekusi query
            Connection conn = KoneksiDB.getConnection();
            String sql = "DELETE FROM antrian WHERE nomor_antrian = ?";
            var ps = conn.prepareStatement(sql);

            ps.setString(1, nomorAntrian);
            ps.execute();

            // Tampilkan pesan jika berhasil menghapus data
            jOptionPane1.showMessageDialog(this, "Data berhasil dihapus!");

            // Perbarui tampilan tabel
            DaftarAntrian daftarAntrian = new DaftarAntrian();
            daftarAntrian.setVisible(true);
        } catch (SQLException e) {
            // Tampilkan pesan kesalahan jika terjadi SQLException
            jOptionPane1.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }


    private void btnUbahactionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        
    }// GEN-LAST:event_jButton2ActionPerformed
 
    // public void isiFormDariTabel(JTable table, javax.swing.JTextField txtNama,
    // javax.swing.JComboBox<String> cbJenisKelamin, javax.swing.JTextField
    // txtAlamat) {
    // int selectedRow = table.getSelectedRow();
    // if (selectedRow != -1) {
    // int nomorAntrian = Integer.parseInt(table.getValueAt(selectedRow,
    // 0).toString());
    // String nama = table.getValueAt(selectedRow, 1).toString();
    // String jenisKelamin = table.getValueAt(selectedRow, 2).toString();
    // String alamat = table.getValueAt(selectedRow, 3).toString();
    //
    // // Buka FormAntrian dan isi data
    // FormAntrian formAntrian = new FormAntrian();
    // formAntrian.setVisible(true);
    // formAntrian.jTextField1.setText(nama);
    // formAntrian.jComboBox1.setSelectedItem(jenisKelamin);
    // formAntrian.jTextField2.setText(alamat);

    //
    // // Simpan nomor antrian ke dalam form untuk keperluan update
    // formAntrian.nomor_antrian(nomorAntrian);
    // }
    // }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarAntrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelAntrian;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbPencarian;
    // End of variables declaration//GEN-END:variables
}
